version: "2"

services:
  cbdemo:
    image: corebos/demo:latest
    environment:
      - COREBOS_DBSERVER=db
      - COREBOS_DBNAME=cbdemo
      - COREBOS_DBUSER=root
      - COREBOS_DBPASS=rootpass
      #- COREBOS_SITEURL=
    restart: always
    volumes:
      - ./storage:/var/www/html/storage
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=cbdemo
    volumes:
      - ./cbconf:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=mbdemo
      - MB_DB_PORT=3306
      - MB_DB_USER=root
      - MB_DB_PASS=rootpass
      - MB_DB_HOST=db
